# Generated by Django 5.1.3 on 2025-02-25 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDriveAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_uri', models.URLField(default='https://oauth2.googleapis.com/token')),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=255)),
                ('scopes', models.TextField(default='https://www.googleapis.com/auth/drive')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
