# Generated by Django 5.1.3 on 2025-02-25 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comic_app', '0002_googledriveaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoogleDriveAccount',
        ),
    ]
