# Generated by Django 5.1.3 on 2025-02-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic_app', '0004_googleaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBBackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
