# Generated by Django 5.1.3 on 2025-03-01 15:18

import comic_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comic_app', '0006_userlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='thumbnail',
            field=comic_app.fields.GoogleDriveImageField(upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='comicimage',
            name='image',
            field=comic_app.fields.GoogleDriveImageField(upload_to='detail_images/'),
        ),
    ]
