# Generated by Django 5.1.3 on 2025-03-02 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic_app', '0007_alter_comic_thumbnail_alter_comicimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicimage',
            name='drive_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='comicimage',
            name='uploaded_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comic_app.googleaccount'),
        ),
    ]
