# Generated by Django 5.1.3 on 2025-03-02 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comic_app', '0008_comicimage_drive_file_id_comicimage_uploaded_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comicimage',
            name='drive_file_id',
        ),
        migrations.RemoveField(
            model_name='comicimage',
            name='uploaded_account',
        ),
    ]
